//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesForceWeb.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IDUsuario { get; set; }
        public string Nome { get; set; }
        public string SobreNome { get; set; }
        public string Sexo { get; set; }
        public string Idade { get; set; }
        public string Email_Endereco { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public string Hora { get; set; }
        public string Token { get; set; }
        public System.DateTime DtInclusao { get; set; }
        public Nullable<System.DateTime> DtAlteracao { get; set; }
    }
}
